[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

# Redirecionamentos (opcional, para limpeza de URLs)
[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200